title: Sarah Spurrier # your name (or website title) here
logo: "/images/resize.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a high school Geography Teacher. It is my 21st year teaching 15-17 year olds about Sense of Place and Cultural Landscapes of the World. 
  <br><br>
  Currently studing to earn my Masters in Geospatial Technologies from the University of Oklahoma
  <br><br>
  <a href="www.linkedin.com/in/sarah-spurrier-386a49189">View My LinkedIn Profile</a> 
  
  
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
